### PR TITLE
fix: Return original t in `find_module` if `search_for_token` fails

### LINKED ISSUE #258: Getting "<luafile>: contains no items"
I am trying to generate a documentation for https://github.com/FAForever/fa/tree/develop/lua

To do so I am running from within `E:\git\faforever\fa`

    ldoc lua -d E:\git\faforever\fa-lua-doc\

but all I get is:

    e:\git\faforever\fa\lua\aeon_naval_weapons.lua:1: contains no items
    output written to e:\git\faforever\fa-lua-doc\aeon

However, I can generate documentation for other sub-directories without problems e.g.

    ldoc lua\AI -d E:\git\faforever\fa-lua-doc\AI

works without troubles.

I'd like to generate a documentation for the whole `lua\` directory. How can I make `ldoc` simply run over all files and ignore whether there are items or not? Is that possible?

### PR DESCRIPTION
**Pull request by lionkor**
Fixes #258.

The if block starting at line 400 in ldoc/parse.lua is the problem.
It seems to look for a `module()` call, and then:
- if it finds one, uses that for the module name
- if it doesn't, infers the name from the filename etc.

This means that in all modern Lua code it will infer the name, obviously.
The issue is that in line 402, it calls `lang:find_module(tok, t, v)` (that is `Lua:find_module` from `lang.lua`), which will (for anything that doesn't use `module()`) return `nil, t, v` where `t, v` is from `self:search_for_token(tok, 'iden', 'module', t, v)`.

I know this is a bit to read, but here I believe the issue lies:

`Lang:search_for_token(...)` will return `t` as nil, here's why:

(from `search_for_token`)
```lua
   -- `t` may be nil here, which means it returns `false, nil, v`
   -- if `t` is nil
   return t ~= nil,t,v
```

And `find_module` says:
```lua
   res,t,v = self:search_for_token(tok,'iden','module',t,v)
   -- we know res may be `false` and `t` may be nil at the same time
   if not res then return nil,t,v end
```

We go back to `parse.lua`, line 402:

```lua
            module_found,t,v = lang:find_module(tok,t,v)
```

at this point `module_found` would be nil, and `t` would be nil also.

Now, a few lines down:

```lua
            if not t then
               F:warning('contains no items','warning',1)
               break;
            end -- run out of file!
```

So this is the issue - `t` may VERY well be nil.

Alternatively, we could:

- Remove the entire if statement that causes this warning, but Chestertons Fence speaks against this - I can't quite figure out exactly why this warning and the subsequent `break` need to be there, so I will not remove it.
- Remove the `break` only, and hope nothing relies on this - again, not sure that's the right move.

`t` arbitrarily being set to `nil` seems wrong here, so that's what I fixed, and it fixes the issue with the following reproducible sample:

```lua
--- my function
-- takes nothing and returns nothing
-- @return nothing
function DoNothing()
end

--
Thing = {
}
```

And also seems to work fine for code using `module()`.

### CODE REVIEW

**Comment by lionkor** [comment]
Long story short - we preserve `t` across a function call that will set it to `nil` if it fails, because we expect that it may fail.

File: ldoc/lang.lua [hunk 1]
```diff
@@ -111,9 +111,10 @@ end
 -- that we must infer the module name.
 function Lua:find_module(tok,t,v)
    local res
-   res,t,v = self:search_for_token(tok,'iden','module',t,v)
+   local st
+   res,st,v = self:search_for_token(tok,'iden','module',t,v)
```
Comment (alerque) [inline ldoc/lang.lua:115]: Thanks for tracking this down. I think you've diagnosed it correctly, I do have a small concern this fix will actually clobber `v`. Lets lay this like does not return anything for `res`, and also returns `nil` or whatever in the third position. Unless it *always* returns the same `v` as was passed to it, this is going to mutate `v` whether it fails or succeeds. That may lead to passing the wrong `v` later. Shouldn't this be `_v` or same other more explicit variable and then return `v` if `not res` but pass `_v` to `:parse_module_call()` otherwise?

Comment (lionkor) [reply ldoc/lang.lua:115]: This again goes back to the call to `tnext()` in `search_for_token()`, and I can't really tell if that may clobber `v` -- so I agree, it would make sense to rename it and only "apply" the overriding of that value if its not part of an invalid result.

Comment (lionkor) [reply ldoc/lang.lua]: I decided to do the same with `v` where I create a temporary called `sv` (`s` due to `search_...`). Doesn't seem to break anything, and probably was a bug as you said.

Comment (alerque) [reply ldoc/lang.lua]: That looks better. It might not have ever come up in practice but at least in theory I think that would have been a bug.
